const estadosCidades = {
  "AC": [
    "Acrelândia", "Assis Brasil", "Brasiléia", "Bujari", "Capixaba",
    "Cruzeiro do Sul", "Epitaciolândia", "Feijó", "Jordão", "Mâncio Lima",
    "Manoel Urbano", "Marechal Thaumaturgo", "Plácido de Castro",
    "Porto Acre", "Porto Walter", "Rio Branco", "Rodrigues Alves",
    "Santa Rosa do Purus", "Sena Madureira", "Senador Guiomard",
    "Tarauacá", "Xapuri"
  ],
  "AL": [
    "Água Branca", "Anadia", "Arapiraca", "Atalaia", "Barra de Santo Antônio",
    "Barra de São Miguel", "Batalha", "Belém", "Belo Monte", "Boca da Mata",
    "Branquinha", "Cacimbinhas", "Cajueiro", "Campestre", "Campo Alegre",
    "Campo Grande", "Canapi", "Capela", "Carneiros", "Chã Preta",
    "Coité do Nóia", "Colônia Leopoldina", "Coqueiro Seco", "Coruripe",
    "Craíbas", "Delmiro Gouveia", "Dois Riachos", "Estrela de Alagoas",
    "Feira Grande", "Feliz Deserto", "Flexeiras", "Girau do Poncian",
    "Ibateguara", "Igaci", "Igreja Nova", "Inhapi", "Jacaré dos Homens",
    "Jacuípe", "Japaratinga", "Jaramataia", "Jequiá da Praia", "Joaquim Gomes",
    "Jundiá", "Junqueiro", "Lagoa da Canoa", "Limoeiro de Anadia", "Maceió"
  ],
  "AM": [
    "Alvarães", "Amaturá", "Anamã", "Anori", "Apuí", "Atalaia do Norte",
    "Autazes", "Barcelos", "Barreirinha", "Benjamin Constant", "Beruri",
    "Boa Vista do Ramos", "Boca do Acre", "Borba", "Caapiranga", "Canutama",
    "Carauari", "Careiro", "Careiro da Várzea", "Coari", "Codajás",
    "Eirunepé", "Envira", "Fonte Boa", "Guajará", "Humaitá", "Ipixuna",
    "Iranduba", "Itacoatiara", "Itamarati", "Itapiranga", "Japurá",
    "Juruá", "Jutaí", "Lábrea", "Manacapuru", "Manaquiri", "Manaus",
    "Manicoré", "Maraã", "Maués", "Nhamundá", "Nova Olinda do Norte",
    "Novo Airão", "Novo Aripuanã", "Parintins", "Pauini", "Presidente Figueiredo",
    "Rio Preto da Eva", "Santa Isabel do Rio Negro"
  ],
  "AP": [
    "Amapá", "Calçoene", "Cutias", "Ferreira Gomes", "Itaubal",
    "Laranjal do Jari", "Macapá", "Mazagão", "Oiapoque", "Pedra Branca do Amapari",
    "Porto Grande", "Pracuúba", "Santana", "Serra do Navio", "Tartarugalzinho",
    "Vitória do Jari"
  ],
  "BA": [
    "Abaré", "Acajutiba", "Adustina", "Água Fria", "Aiquara", "Alagoinhas",
    "Alcobaça", "Almadina", "Amargosa", "Amélia Rodrigues", "América Dourada",
    "Anagé", "Andaraí", "Andorinha", "Angical", "Anguera", "Antas",
    "Antônio Cardoso", "Antônio Gonçalves", "Aporá", "Apuarema", "Araças",
    "Aracatu", "Araci", "Aramari", "Arataca", "Aratuípe", "Baianópolis",
    "Baixa Grande", "Banzaê", "Barra", "Barra da Estiva", "Barra do Choça",
    "Barra do Mendes", "Barra do Rocha", "Barreiras", "Barro Alto", "Barrocas",
    "Barro Preto", "Belmonte", "Belo Campo", "Biritinga", "Boa Nova",
    "Boa Vista do Tupim", "Bom Jesus da Lapa", "Bom Jesus da Serra", "Boninal",
    "Bonito", "Boquira", "Botuporã", "Brejões", "Brejolândia"
  ],
  "CE": [
    "Abaiara", "Acarape", "Acaraú", "Acopiara", "Aiuaba", "Alcântaras",
    "Altaneira", "Alto Santo", "Amontada", "Antonina do Norte", "Apuiarés",
    "Aquiraz", "Aracati", "Aracoiaba", "Ararendá", "Araripe", "Aratuba",
    "Arneiroz", "Assaré", "Aurora", "Baixio", "Banabuiú", "Barbalha",
    "Barreira", "Barro", "Barroquinha", "Baturité", "Beberibe",
    "Bela Cruz", "Boa Viagem", "Brejo Santo", "Camocim", "Campos Sales",
    "Canindé", "Capistrano", "Caridade", "Cariré", "Caririaçu", "Cariús",
    "Carnaubal", "Cascavel", "Catarina", "Caucaia", "Cedro", "Chaval",
    "Choró", "Chorozinho", "Coreaú", "Crateús", "Crato", "Frecheirinha"
  ],
  "DF": [
    "Brasília"
  ],
  "ES": [
    "Água Doce do Norte", "Águia Branca", "Alfredo Chaves", "Alto Rio Novo",
    "Anchieta", "Apiacá", "Aracruz", "Atílio Vivácqua", "Baixo Guandu",
    "Barra de São Francisco", "Boa Esperança", "Bom Jesus do Norte",
    "Brejetuba", "Cachoeiro de Itapemirim", "Cariacica", "Castelo",
    "Colatina", "Conceição da Barra", "Conceição do Castelo", "Divino de São Lourenço",
    "Domingos Martins", "Dores do Rio Preto", "Ecoporanga", "Fundão",
    "Guaçuí", "Guarapari", "Ibatiba", "Ibiraçu", "Ibitirama", "Iconha",
    "Irupi", "Itaguaçu", "Itapemirim", "Itarana", "Iúna", "Jaguaré",
    "Jerônimo Monteiro", "João Neiva", "Laranja da Terra", "Linhares",
    "Mantenópolis", "Marataízes", "Marechal Floriano", "Marilândia",
    "Mimoso do Sul", "Montanha", "Mucurici", "Muniz Freire", "Muqui",
    "Nova Venécia"
  ],
  "GO": [
    "Abadia de Goiás", "Abadiânia", "Acreúna", "Adelândia", "Água Fria de Goiás",
    "Água Limpa", "Águas Lindas de Goiás", "Alexânia", "Aloândia", "Alto Horizonte",
    "Alto Paraíso de Goiás", "Alvorada", "Amaralina", "Americano do Brasil",
    "Amorinópolis", "Anápolis", "Anhanguera", "Anicuns", "Aparecida de Goiânia",
    "Aparecida do Rio Doce", "Aporé", "Araçu", "Aragarças", "Aragoiânia",
    "Araguapaz", "Arenópolis", "Aruanã", "Aurilândia", "Avelinópolis",
    "Baliza", "Barro Alto", "Bela Vista de Goiás", "Bom Jardim de Goiás",
    "Bom Jesus de Goiás", "Bonfinópolis", "Bonópolis", "Brazabrantes",
    "Britânia", "Buriti Alegre", "Buriti de Goiás", "Buritinópolis",
    "Cabeceiras", "Cachoeira Alta", "Cachoeira de Goiás", "Cachoeira Dourada",
    "Caçu", "Caiapônia", "Caldas Novas", "Caldazinha", "Campestre de Goiás",
    "Campinaçu"
  ],
  "MA": [
    "Açailândia", "Afonso Cunha", "Água Doce do Maranhão", "Alcântara",
    "Aldeias Altas", "Altamira do Maranhão", "Alto Alegre do Maranhão",
    "Alto Alegre do Pindaré", "Alto Parnaíba", "Amapá do Maranhão",
    "Amarante do Maranhão", "Anajatuba", "Anapurus", "Apicum-Açu",
    "Araguanã", "Araioses", "Arame", "Arari", "Axixá", "Bacabal",
    "Bacabeira", "Bacuri", "Bacurituba", "Balsas", "Barra do Corda",
    "Barreirinhas", "Bela Vista do Maranhão", "Belágua", "Benedito Leite",
    "Bequimão", "Bernardo do Mearim", "Boa Vista do Gurupi", "Bom Jardim",
    "Bom Jesus das Selvas", "Bom Lugar", "Brejo", "Brejo de Areia",
    "Buriti", "Buriti Bravo", "Buriticupu", "Buritirana", "Cachoeira Grande",
    "Cajapió", "Cajari", "Campestre do Maranhão", "Cândido Mendes",
    "Cantanhede", "Capinzal do Norte", "Carolina", "Carutapera", "Caxias",
    "Cedral"
  ],
  "MG": [
    "Abadia dos Dourados", "Abaeté", "Abre Campo", "Acaiaca", "Açucena",
    "Água Boa", "Água Comprida", "Aguanil", "Águas Formosas", "Águas Vermelhas",
    "Aimorés", "Aiuruoca", "Alagoa", "Albertina", "Além Paraíba",
    "Alfenas", "Almenara", "Alpercata", "Alpinópolis", "Alterosa",
    "Alto Caparaó", "Alto Jequitibá", "Alto Rio Novo", "Alvorada de Minas",
    "Andradas", "Andrelândia", "Angelândia", "Antônio Carlos",
    "Antônio Dias", "Antônio Prado de Minas", "Araçaí", "Aracitaba",
    "Araçuaí", "Araguari", "Arantina", "Araponga", "Araporã", "Arapuá",
    "Araújos", "Araxá", "Arceburgo", "Arcos", "Areado", "Argirita",
    "Aricanduva", "Arinos", "Astolfo Dutra", "Ataléia", "Augusto de Lima",
    "Baependi", "Baldim"
  ],
  "MS": [
    "Água Clara", "Alcinópolis", "Amambaí", "Anastácio", "Anaurilândia",
    "Angélica", "Antônio João", "Aparecida do Taboado", "Aquidauana",
    "Aral Moreira", "Bandeirantes", "Batayporã", "Bela Vista", "Bodoquena",
    "Bonito", "Brasilândia", "Caarapó", "Camapuã", "Campo Grande",
    "Caracol", "Cassilândia", "Chapadão do Sul", "Corguinho", "Coronel Sapucaia",
    "Corumbá", "Costa Rica", "Coxim", "Deodápolis", "Dois Irmãos do Buriti",
    "Douradina", "Dourados", "Eldorado", "Fátima do Sul", "Figueirão",
    "Glória de Dourados", "Guia Lopes da Laguna", "Iguatemi", "Inocência",
    "Itaporã", "Itaquiraí", "Ivinhema", "Japorã", "Jaraguari", "Jardim",
    "Jateí", "Juti", "Ladário", "Laguna Carapã", "Maracaju", "Miranda"
  ],
  "MT": [
    "Acorizal", "Água Boa", "Alta Floresta", "Alto Araguaia", "Alto Boa Vista",
    "Alto Garças", "Alto Paraguai", "Alto Taquari", "Apiacás", "Araguaiana",
    "Araguainha", "Araputanga", "Arenápolis", "Aripuanã", "Barão de Melgaço",
    "Barra do Bugres", "Barra do Garças", "Artur Nogueira", "Bom Jesus do Araguaia",
    "Brasnorte", "Cáceres", "Campinápolis", "Campo Novo do Parecis",
    "Campo Verde", "Campos de Júlio", "Canabrava do Norte", "Canarana",
    "Carlinda", "Castanheira", "Chapada dos Guimarães", "Cláudia",
    "Cocalinho", "Colíder", "Colniza", "Comodoro", "Confresa", "Conquista D'Oeste",
    "Cotriguaçu", "Cuiabá", "Curvelândia", "Denise", "Diamantino",
    "Dom Aquino", "Feliz Natal", "Figueirópolis D'Oeste", "Gaúcha do Norte",
    "General Carneiro", "Glória D'Oeste", "Guarantã do Norte", "Guiratinga",
    "Indiavaí", "Ipiranga do Norte", "Itanhangá", "Itaúba", "Itiquira"
  ],
  "PA": [
    "Abaetetuba", "Abel Figueiredo", "Acará", "Afuá", "Água Azul do Norte",
    "Alenquer", "Almeirim", "Altamira", "Anajás", "Ananindeua",
    "Anapu", "Augusto Corrêa", "Aurora do Pará", "Aveiro", "Bagre",
    "Baião", "Bannach", "Barcarena", "Belém", "Belterra",
    "Benevides", "Bom Jesus do Tocantins", "Bonito", "Bragança",
    "Brasil Novo", "Brejo Grande do Araguaia", "Breu Branco", "Cametá",
    "Canaã dos Carajás", "Capanema", "Capitão Poço", "Chaves",
    "Colares", "Conceição do Araguaia", "Concórdia do Pará", "Curuá",
    "Curuçá", "Dom Eliseu", "Eldorado dos Carajás", "Faro",
    "Floresta do Araguaia", "Garrafão do Norte", "Goianésia do Pará",
    "Gurupá", "Igarapé-Açu", "Igarapé-Miri", "Inhangapi", "Ipixuna do Pará",
    "Irituia", "Itupiranga", "Jacareacanga"
  ],
  "PB": [
    "Água Branca", "Aguiar", "Alagoa Grande", "Alagoa Nova", "Alagoinha",
    "Alcantil", "Algodão de Jandaíra", "Alhandra", "Amparo", "Aparecida",
    "Araçagi", "Arara", "Araruna", "Areia", "Areia de Baraúnas",
    "Areial", "Aroeiras", "Assunção", "Baía da Traição", "Bananeiras",
    "Baraúna", "Barra de Santa Rosa", "Barra de Santana", "Barra de São Miguel",
    "Bayeux", "Bernardino Batista", "Boa Ventura", "Boa Vista", "Bom Jesus",
    "Bom Sucesso", "Bonito de Santa Fé", "Boqueirão", "Borborema",
    "Brejo do Cruz", "Brejo dos Santos", "Caaporã", "Cabaceiras",
    "Cabedelo", "Cachoeira dos Índios", "Cacimba de Areia",
    "Cacimba de Dentro", "Cacimbas", "Caiçara", "Cajazeiras", "Cajazeirinhas",
    "Caldas Brandão", "Camalaú", "Campina Grande", "Capim", "Caraúbas"
  ],
  "PE": [
    "Afogados da Ingazeira", "Afrânio", "Agrestina", "Água Preta", "Águas Belas",
    "Alagoinha", "Altinho", "Amaraji", "Angelim", "Araçoiaba",
    "Araripina", "Arcoverde", "Barra de Guabiraba", "Barreiros", "Belém de Maria",
    "Belém do São Francisco", "Belo Jardim", "Betânia", "Bezerros",
    "Bodocó", "Bom Conselho", "Bom Jardim", "Bonito", "Brejão",
    "Brejinho", "Brejo da Madre de Deus", "Buenos Aires", "Buíque",
    "Cabo de Santo Agostinho", "Cabrobó", "Cachoeirinha", "Caetés",
    "Caetés", "Calçados", "Calumbi", "Camaragibe", "Camocim de São Félix",
    "Camutanga", "Canhotinho", "Capoeiras", "Carnaíba", "Carnaubeira da Penha",
    "Carpina", "Caruaru", "Casinhas", "Catende", "Cedro", "Chã Grande",
    "Chã de Alegria", "Condado", "Correntes"
  ],
  "PI": [
    "Acauã", "Agricolândia", "Água Branca", "Alagoinha do Piauí", "Alegrete do Piauí",
    "Alto Longá", "Altos", "Alvorada do Gurguéia", "Amarante", "Angical do Piauí",
    "Anísio de Abreu", "Antônio Almeida", "Aroazes", "Arraial", "Assunção do Piauí",
    "Avelino Lopes", "Baixa Grande do Ribeiro", "Barra D'Alcântara",
    "Barras", "Barreiras do Piauí", "Barro Duro", "Batalha", "Bela Vista do Piauí",
    "Belém do Piauí", "Beneditinos", "Bertolínia", "Betânia do Piauí",
    "Boa Hora", "Bocaina", "Bom Jesus", "Bom Princípio do Piauí",
    "Bonfim do Piauí", "Boqueirão do Piauí", "Brasileira", "Brejo do Piauí",
    "Buriti dos Lopes", "Buriti dos Montes", "Cabeceiras do Piauí",
    "Cajazeiras do Piauí", "Cajueiro da Praia", "Caldeirão Grande do Piauí",
    "Campinas do Piauí", "Campo Alegre do Fidalgo", "Campo Grande do Piauí",
    "Campo Largo do Piauí", "Campo Maior", "Canavieira", "Canto do Buriti",
    "Capitão de Campos", "Capitão Gervásio Oliveira", "Caraúbas do Piauí"
  ],
  "PR": [
    "Abatiá", "Adrianópolis", "Agudos do Sul", "Almirante Tamandaré",
    "Altamira do Paraná", "Alto Paraíso", "Alto Paraná", "Alto Piquiri",
    "Alvorada do Sul", "Amaporã", "Andirá", "Ângulo", "Antonina",
    "Antônio Olinto", "Apucarana", "Arapongas", "Arapoti", "Arapuã",
    "Araruna", "Araucária", "Ariranha do Ivaí", "Assaí", "Assis Chateaubriand",
    "Astorga", "Atalaia", "Balsa Nova", "Bandeirantes", "Barbosa Ferraz",
    "Barracão", "Barra do Jacaré", "Bela Vista do Paraíso", "Boa Esperança",
    "Boa Esperança do Iguaçu", "Boa Ventura de São Roque", "Boa Vista da Aparecida",
    "Bocaiúva do Sul", "Bom Jesus do Sul", "Bom Sucesso", "Bom Sucesso do Sul",
    "Borrazópolis", "Braganey", "Brasilândia do Sul", "Cafeara", "Cafélandia",
    "Cafezal do Sul", "Cambará", "Cambé", "Cambira", "Campina da Lagoa",
    "Campina do Simão", "Campina Grande do Sul"
  ],
  "RJ": [
    "Angra dos Reis", "Aperibé", "Araruama", "Areal", "Armação dos Búzios",
    "Arraial do Cabo", "Barra do Piraí", "Barra Mansa", "Belford Roxo",
    "Bom Jardim", "Bom Jesus do Itabapoana", "Cabo Frio", "Cachoeiras de Macacu",
    "Cambuci", "Campos dos Goytacazes", "Cantagalo", "Carapebus",
    "Cardoso Moreira", "Carmo", "Casimiro de Abreu", "Comendador Levy Gasparian",
    "Conceição de Macabu", "Cordeiro", "Duas Barras", "Duque de Caxias",
    "Engenheiro Paulo de Frontin", "Guapimirim", "Iguaba Grande", "Itaboraí",
    "Itaguaí", "Italva", "Itaocara", "Itaperuna", "Itatiaia", "Japeri",
    "Laje do Muriaé", "Macaé", "Macuco", "Magé", "Mangaratiba",
    "Maricá", "Mendes", "Mesquita", "Miguel Pereira", "Miracema",
    "Natividade", "Nilópolis", "Niterói", "Nova Friburgo", "Nova Iguaçu",
    "Paracambi"
  ],
  "RN": [
    "Acari", "Açu", "Afonso Bezerra", "Água Nova", "Alexandria",
    "Almino Afonso", "Alto do Rodrigues", "Angicos", "Antônio Martins",
    "Apodi", "Areia Branca", "Arês", "Augusto Severo", "Baía Formosa",
    "Baraúna", "Barcelona", "Bento Fernandes", "Bodó", "Bom Jesus",
    "Portalegre", "Brejinho", "Caiçara do Norte", "Caiçara do Rio do Vento",
    "Caicó", "Campo Grande", "Campo Redondo", "Canguaretama",
    "Caraúbas", "Carnaúba dos Dantas", "Carnaubais", "Ceará-Mirim",
    "Cerro Corá", "Coronel Ezequiel", "Coronel João Pessoa", "Cruzeta",
    "Currais Novos", "Doutor Severiano", "Encanto", "Equador",
    "Espírito Santo", "Extremoz", "Felipe Guerra", "Fernando Pedroza",
    "Florânia", "Francisco Dantas", "Frutuoso Gomes", "Galinhos",
    "Goianinha", "Governador Dix-Sept Rosado", "Grossos", "Guamaré",
    "Ielmo Marinho", "Ipanguaçu"
  ],
  "RO": [
    "Alta Floresta D'Oeste", "Alto Paraíso", "Alvorada D'Oeste", "Ariquemes",
    "Cabixi", "Cacaulândia", "Cacoal", "Campo Novo de Rondônia",
    "Candeias do Jamari", "Castanheiras", "Cerejeiras", "Chupinguaia",
    "Colorado do Oeste", "Corumbiara", "Costa Marques", "Cujubim",
    "Espigão D'Oeste", "Governador Jorge Teixeira", "Guajará-Mirim",
    "Itapuã do Oeste", "Jaru", "Ji-Paraná", "Machadinho D'Oeste",
    "Ministro Andreazza", "Mirante da Serra", "Monte Negro", "Nova Brasilândia D'Oeste",
    "Nova Mamoré", "Nova União", "Novo Horizonte D'Oeste", "Ouro Preto do Oeste",
    "Parecis", "Pimenta Bueno", "Pimenteiras do Oeste", "Porto Velho",
    "Presidente Médici", "Primavera de Rondônia", "Rio Crespo",
    "Rolim de Moura", "Santa Luzia D'Oeste", "São Felipe D'Oeste",
    "São Francisco do Guaporé", "São Miguel do Guaporé", "Seringueiras",
    "Teixeirópolis", "Theobroma", "Urupá", "Vale do Anari", "Vale do Paraíso",
    "Vilhena"
  ],
  "RR": [
    "Alto Alegre", "Amajari", "Boa Vista", "Bonfim", "Cantá",
    "Caracaraí", "Caroebe", "Iracema", "Mucajaí", "Normandia",
    "Pacaraima", "Rorainópolis", "São João da Baliza", "São Luiz",
    "Uiramutã"
  ],
  "RS": [
    "Aceguá", "Água Santa", "Agudo", "Ajuricaba", "Alecrim", "Alegrete",
    "Alegria", "Almirante Tamandaré do Sul", "Alpestre", "Alto Alegre",
    "Alto Feliz", "Alto Santa Fé", "Alvorada", "Amaral Ferrador",
    "Ametista do Sul", "André da Rocha", "Anta Gorda", "Antônio Prado",
    "Arambaré", "Araricá", "Aratiba", "Arroio do Meio", "Arroio do Sal",
    "Arroio do Padre", "Arroio dos Ratos", "Arroio Grande", "Arvorezinha",
    "Augusto Pestana", "Áurea", "Bagé", "Balneário Pinhal", "Barão",
    "Barão de Cotegipe", "Barão do Triunfo", "Barra do Guarita",
    "Barra do Quaraí", "Barra do Ribeiro", "Barra do Rio Azul",
    "Barra Funda", "Barracão", "Barros Cassal", "Benjamin Constant do Sul",
    "Bento Gonçalves", "Boa Vista das Missões", "Boa Vista do Buricá",
    "Boa Vista do Cadeado", "Boa Vista do Incra", "Boa Vista do Sul",
    "Bom Jesus", "Bom Princípio", "Bom Progresso"
  ],
  "SC": [
    "Abdon Batista", "Abelardo Luz", "Agrolândia", "Agronômica", "Água Doce",
    "Águas de Chapecó", "Águas Frias", "Águas Mornas", "Alfredo Wagner",
    "Alto Bela Vista", "Anchieta", "Angelina", "Anita Garibaldi",
    "Anitápolis", "Antônio Carlos", "Apiti", "Arabutã", "Araquari",
    "Araranguá", "Armazém", "Arroio Trinta", "Arvoredo", "Ascurra",
    "Atalanta", "Aurora", "Balneário Arroio do Silva",
    "Balneário Barra do Sul", "Balneário Camboriú", "Balneário Gaivota",
    "Bandeirante", "Barra Bonita", "Barra Velha", "Bela Vista do Toldo",
    "Benedito Novo", "Biguaçu", "Blumenau", "Bocaina do Sul", "Bom Jardim da Serra",
    "Bom Jesus", "Bom Jesus do Oeste", "Bom Retiro", "Botuverá",
    "Braço do Norte", "Braço do Trombudo", "Brunópolis", "Brusque",
    "Caçador", "Caibi", "Calmon", "Camboriú", "Campo Alegre", "Campo Belo do Sul"
  ],
  "SE": [
    "Amparo do São Francisco", "Aquidabã", "Aracaju", "Arauá", "Areia Branca",
    "Barra dos Coqueiros", "Boquim", "Brejo Grande", "Campo do Brito",
    "Canhoba", "Canindé de São Francisco", "Capela", "Carira", "Carmópolis",
    "Cedro de São João", "Cristinápolis", "Cumbe", "Divina Pastora",
    "Estância", "Feira Nova", "Frei Paulo", "Gararu", "General Maynard",
    "Graccho Cardoso", "Ilha das Flores", "Indiaroba", "Itabaiana",
    "Itabaianinha", "Itabi", "Itaporanga D'Ajuda", "Japaratuba", "Japoatã",
    "Lagarto", "Laranjeiras", "Malhada dos Bois", "Malhador", "Maruim",
    "Moita Bonita", "Monte Alegre de Sergipe", "Muribeca", "Neópolis",
    "Nossa Senhora Aparecida", "Nossa Senhora da Glória",
    "Nossa Senhora das Dores", "Nossa Senhora de Lourdes",
    "Nossa Senhora do Socorro", "Pacatuba", "Palmares", "Pinhão",
    "Pirambu", "Poço Redondo"
  ],
  "SP": [
    "Adamantina", "Adolfo", "Aguaí", "Águas da Prata", "Águas de Lindóia",
    "Águas de Santa Bárbara", "Águas de São Pedro", "Agudos", "Alambari",
    "Alfredo Marcondes", "Altair", "Altinópolis", "Alto Alegre", "Alumínio",
    "Álvares Florence", "Álvares Machado", "Álvaro de Carvalho", "Alvinlândia",
    "Americana", "Américo Brasiliense", "Américo de Campos", "Amparo",
    "Analândia", "Andradina", "Angatuba", "Anhembi", "Anhumas", "Apiaí",
    "Araçariguama", "Araçatuba", "Araçoiaba da Serra", "Arad", "Araraquara",
    "Araras", "Arco-Íris", "Arealva", "Areias", "Areiópolis", "Ariranha",
    "Artur Nogueira", "Arujá", "Aspásia", "Assis", "Atibaia", "Auriflama",
    "Avaí", "Avanhandava", "Avaré", "Bady Bassitt", "Balbinópolis"
  ],
  "TO": [
    "Abreulândia", "Aguiarnópolis", "Aliança do Tocantins", "Almas",
    "Alvorada", "Ananás", "Angico", "Aparecida do Rio Negro", "Aragominas",
    "Araguacema", "Araguaçu", "Araguaína", "Araguatins", "Arapoema",
    "Arraias", "Augustinópolis", "Aurora do Tocantins", "Axixá do Tocantins",
    "Babaçulândia", "Bandeirantes do Tocantins", "Barra do Ouro",
    "Barrolândia", "Bernardo Sayão", "Bom Jesus do Tocantins", "Brasilândia do Tocantins",
    "Brejinho de Nazaré", "Buriti do Tocantins", "As 100 primeiras cidades do Tocantins em ordem alfabética.",
    "Cachoeirinha", "Caseara", "Centenário", "Chapada de Areia",
    "Chapada da Natividade", "Colinas do Tocantins", "Colméia",
    "Combinado", "Conceição do Tocantins", "Couto de Magalhães",
    "Cristalândia", "Crixás do Tocantins", "Darcinópolis", "Dianópolis",
    "Divinópolis do Tocantins", "Dois Irmãos do Tocantins",
    "Dueré", "Esperantina", "Fátima", "Figueirópolis", "Filadélfia",
    "Formoso do Araguaia", "Goianorte", "Goiatins", "Guaraí", "Gurupi"
  ]
};