
const estadosCidades = {
  "AC": ["Rio Branco", "Cruzeiro do Sul"],
  "AL": ["Maceió", "Arapiraca"],
  "AM": ["Manaus", "Parintins"],
  "AP": ["Macapá", "Santana"],
  "BA": ["Salvador", "Feira de Santana", "Vitória da Conquista"],
  "CE": ["Fortaleza", "Juazeiro do Norte", "Frecheirinha"],
  "DF": ["Brasília"],
  "ES": ["Vitória", "Vila Velha"],
  "GO": ["Goiânia", "Anápolis"],
  "MA": ["São Luís", "Imperatriz"],
  "MG": ["Belo Horizonte", "Uberlândia", "Contagem"],
  "MS": ["Campo Grande", "Dourados"],
  "MT": ["Cuiabá", "Várzea Grande"],
  "PA": ["Belém", "Santarém"],
  "PB": ["João Pessoa", "Campina Grande"],
  "PE": ["Recife", "Olinda"],
  "PI": ["Teresina", "Parnaíba"],
  "PR": ["Curitiba", "Londrina"],
  "RJ": ["Rio de Janeiro", "Niterói"],
  "RN": ["Natal", "Mossoró"],
  "RO": ["Porto Velho", "Ji-Paraná"],
  "RR": ["Boa Vista"],
  "RS": ["Porto Alegre", "Caxias do Sul"],
  "SC": ["Florianópolis", "Joinville"],
  "SE": ["Aracaju", "Nossa Senhora do Socorro"],
  "SP": ["São Paulo", "Campinas", "Santos"],
  "TO": ["Palmas", "Araguaína"]
};
